apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-deployment
spec:
  selector:
    matchLabels:
      app: personmongodb
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: personmongodb
    spec:
      containers:
      - name: personmongodb
        image: smburu2019/personmongodb
        ports:
        - containerPort: 80
